site_name: Chen`s projects

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

copyright: Copyright &copy; 2023 Chen Chuncan

nav:
  - Home: index.md
  - Blog:
    - Blog: Blog/blog.md
    - Algorithm:
      - Leetcode: Blog/Algorithm/leetcode.md
      - Sorting: Blog/Algorithm/sorting.md
    - Front-end:
      - JavaScript: Blog/Front-end/javascript.md
  - VITON-GSP:
    - Introduction: VTON-GSP/Introduction.md
    - Virtual Try-on: VTON-GSP/VTON.md
  - 鞋厂ERP:
    - 简介: 鞋厂ERP/Introduction.md